// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef INTAKE_H
#define INTAKE_H
#include "frc/commands/Subsystem.h"
#include "frc/WPILib.h"
#include "LightDriveCAN.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Intake: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	//std::shared_ptr<frc::DoubleSolenoid> hatch;
	//std::shared_ptr<frc::DoubleSolenoid> clawTilt;
	//std::shared_ptr<frc::DoubleSolenoid> clawExtend;
	std::shared_ptr<frc::SpeedController> cargoMotor1;
	std::shared_ptr<frc::SpeedController> cargoMotor2;
	//std::shared_ptr<frc::SpeedControllerGroup> cargo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Intake();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	std::shared_ptr<frc::SpeedControllerGroup> cargo;
	std::shared_ptr<frc::DoubleSolenoid> hatch;
	std::shared_ptr<frc::DoubleSolenoid> clawTilt;
	std::shared_ptr<frc::DoubleSolenoid> clawExtend;

	std::shared_ptr<LightDriveCAN> leds;
};

#endif
