// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "frc/WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	
	
	std::shared_ptr<frc::Joystick> co-Pilot;
	std::shared_ptr<frc::JoystickButton> leftJoystickLuke;
	std::shared_ptr<frc::Joystick> driver;
	std::shared_ptr<frc::JoystickButton> leftJoystickWill;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getDriver();
	std::shared_ptr<frc::Joystick> getCo-Pilot();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	static const int LEFT_Y_AXIS = 1;
	static const int RIGHT_Y_AXIS = 5;
};

#endif
