// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/Premade4.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Premade4::Premade4(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Premade4::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Premade4::Execute() {
    angleError = Robot::arm->Get_Angle() - angleGoal;
    angleProportion = angleError / angleGoal;
    if (angleError > 0){
        Robot::arm->armMotor->Set(-angleProportion - 0.2);
    }
    else{
        Robot::arm->armMotor->Set(angleProportion + 0.2);
    }

}

// Make this return true when this Command no longer needs to run execute()
bool Premade4::IsFinished() {
    return !Robot::intake->breakBeam->Get();
    if (abs(angleError) < Robot::arm->ERROR_MARGIN){
        return true;
    }
    return false;
}

// Called once after isFinished returns true
void Premade4::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Premade4::Interrupted() {

}
